const INHERITED_PROPERTIES = new Set([
  'accent-color',
  'border-collapse',
  'border-spacing',
  'caption-side',
  'caret-color',
  'color',
  'color-scheme',
  'cursor',
  'direction',
  'empty-cells',
  'font',
  'font-family',
  'font-feature-settings',
  'font-kerning',
  'font-language-override',
  'font-optical-sizing',
  'font-palette',
  'font-size',
  'font-size-adjust',
  'font-stretch',
  'font-style',
  'font-synthesis',
  'font-variant',
  'font-variant-alternates',
  'font-variant-caps',
  'font-variant-east-asian',
  'font-variant-emoji',
  'font-variant-ligatures',
  'font-variant-numeric',
  'font-variant-position',
  'font-variation-settings',
  'font-weight',
  'forced-color-adjust',
  'hanging-punctuation',
  'hyphenate-character',
  'hyphenate-limit-chars',
  'hyphens',
  'image-orientation',
  'image-rendering',
  'letter-spacing',
  'line-break',
  'line-height',
  'list-style',
  'list-style-image',
  'list-style-position',
  'list-style-type',
  'math-depth',
  'math-shift',
  'math-style',
  'orphans',
  'overflow-wrap',
  'paint-order',
  'pointer-events',
  'print-color-adjust',
  'quotes',
  'ruby-align',
  'ruby-position',
  'scrollbar-color',
  'speak',
  'tab-size',
  'text-align',
  'text-align-last',
  'text-combine-upright',
  'text-decoration-skip-ink',
  'text-emphasis',
  'text-emphasis-color',
  'text-emphasis-position',
  'text-emphasis-style',
  'text-indent',
  'text-justify',
  'text-orientation',
  'text-rendering',
  'text-shadow',
  'text-size-adjust',
  'text-spacing-trim',
  'text-transform',
  'text-underline-offset',
  'text-underline-position',
  'text-wrap',
  'text-wrap-mode',
  'text-wrap-style',
  'visibility',
  'white-space',
  'white-space-collapse',
  'widows',
  'word-break',
  'word-spacing',
  'word-wrap',
  'writing-mode',
]);

const WEBKIT_INHERITED = new Set([
  '-webkit-font-smoothing',
  '-webkit-text-stroke',
  '-webkit-text-stroke-color',
  '-webkit-text-stroke-width',
]);

export function isInheritable(name: string): boolean {
  if (name.startsWith('--')) return true;
  const lower = name.toLowerCase();
  if (WEBKIT_INHERITED.has(lower)) return true;
  const canonical = lower.replace(/^-(webkit|moz|ms|o|epub)-/, '');
  return INHERITED_PROPERTIES.has(canonical);
}
