import type { Lhr } from '../../src/audit/types.js';

export function makeLhr(over: Partial<Lhr> = {}): Lhr {
  return {
    requestedUrl: 'http://localhost:8901/fixture.html',
    finalDisplayedUrl: 'http://localhost:8901/fixture.html',
    fetchTime: '2026-07-19T10:00:00.000Z',
    lighthouseVersion: '13.4.0',
    configSettings: { formFactor: 'mobile' },
    categories: {
      performance: {
        id: 'performance',
        title: 'Performance',
        score: 0.92,
        auditRefs: [
          { id: 'largest-contentful-paint', weight: 25, group: 'metrics' },
          { id: 'total-blocking-time', weight: 30, group: 'metrics' },
          { id: 'cumulative-layout-shift', weight: 25, group: 'metrics' },
          { id: 'first-contentful-paint', weight: 10, group: 'metrics' },
          { id: 'speed-index', weight: 10, group: 'metrics' },
          { id: 'render-blocking-resources', weight: 0 },
          { id: 'unused-javascript', weight: 0 },
        ],
      },
      accessibility: {
        id: 'accessibility',
        title: 'Accessibility',
        score: 0.85,
        auditRefs: [
          { id: 'image-alt', weight: 10 },
          { id: 'label', weight: 10 },
          { id: 'color-contrast', weight: 7 },
        ],
      },
      'best-practices': {
        id: 'best-practices',
        title: 'Best Practices',
        score: 1,
        auditRefs: [{ id: 'errors-in-console', weight: 1 }],
      },
      seo: {
        id: 'seo',
        title: 'SEO',
        score: 0.67,
        auditRefs: [
          { id: 'meta-description', weight: 5 },
          { id: 'document-title', weight: 5 },
        ],
      },
    },
    audits: {
      'largest-contentful-paint': {
        id: 'largest-contentful-paint',
        title: 'Largest Contentful Paint',
        score: 0.95,
        scoreDisplayMode: 'numeric',
        displayValue: '1.8 s',
        numericValue: 1834.5,
        numericUnit: 'millisecond',
      },
      'total-blocking-time': {
        id: 'total-blocking-time',
        title: 'Total Blocking Time',
        score: 1,
        scoreDisplayMode: 'numeric',
        displayValue: '40 ms',
        numericValue: 41.2,
        numericUnit: 'millisecond',
      },
      'cumulative-layout-shift': {
        id: 'cumulative-layout-shift',
        title: 'Cumulative Layout Shift',
        score: 0.98,
        scoreDisplayMode: 'numeric',
        displayValue: '0.02',
        numericValue: 0.021,
        numericUnit: 'unitless',
      },
      'first-contentful-paint': {
        id: 'first-contentful-paint',
        title: 'First Contentful Paint',
        score: 0.99,
        scoreDisplayMode: 'numeric',
        displayValue: '0.9 s',
        numericValue: 912.3,
        numericUnit: 'millisecond',
      },
      'speed-index': {
        id: 'speed-index',
        title: 'Speed Index',
        score: 0.97,
        scoreDisplayMode: 'numeric',
        displayValue: '1.2 s',
        numericValue: 1200,
        numericUnit: 'millisecond',
      },
      'render-blocking-resources': {
        id: 'render-blocking-resources',
        title: 'Eliminate render-blocking resources',
        description: 'Resources are blocking the first paint. [Learn more](https://web.dev/render-blocking-resources/).',
        score: 0.45,
        scoreDisplayMode: 'metricSavings',
        displayValue: 'Potential savings of 310 ms',
        details: {
          type: 'opportunity',
          overallSavingsMs: 310,
          headings: [
            { key: 'url', valueType: 'url', label: 'URL' },
            { key: 'totalBytes', valueType: 'bytes', label: 'Size' },
            { key: 'wastedMs', valueType: 'timespanMs', label: 'Savings' },
          ],
          items: [
            { url: 'http://localhost:8901/blocking.css', totalBytes: 20480, wastedMs: 310 },
          ],
        },
      },
      'unused-javascript': {
        id: 'unused-javascript',
        title: 'Reduce unused JavaScript',
        score: 1,
        scoreDisplayMode: 'metricSavings',
        details: { type: 'opportunity', overallSavingsMs: 0, overallSavingsBytes: 0, items: [] },
      },
      'image-alt': {
        id: 'image-alt',
        title: 'Image elements have `[alt]` attributes',
        description: 'Informative elements should aim for short, descriptive alternate text.',
        score: 0,
        scoreDisplayMode: 'binary',
        details: {
          type: 'table',
          headings: [{ key: 'node', valueType: 'node', label: 'Failing Elements' }],
          items: [{ node: { selector: 'img.hero', snippet: '<img class="hero" src="a.png">' } }],
        },
      },
      label: {
        id: 'label',
        title: 'Form elements have associated labels',
        score: null,
        scoreDisplayMode: 'notApplicable',
      },
      'color-contrast': {
        id: 'color-contrast',
        title: 'Background and foreground colors have a sufficient contrast ratio',
        description: 'Low-contrast text is difficult or impossible for many users to read.',
        score: 0.5,
        scoreDisplayMode: 'binary',
      },
      'errors-in-console': {
        id: 'errors-in-console',
        title: 'No browser errors logged to the console',
        score: 1,
        scoreDisplayMode: 'binary',
      },
      'meta-description': {
        id: 'meta-description',
        title: 'Document has a meta description',
        description: 'Meta descriptions may be included in search results.',
        score: 0,
        scoreDisplayMode: 'binary',
      },
      'document-title': {
        id: 'document-title',
        title: 'Document has a `<title>` element',
        score: 1,
        scoreDisplayMode: 'binary',
      },
    },
    runWarnings: [],
    ...over,
  };
}
